# Generated by Django 5.0.9 on 2024-11-01 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='inventory_name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory'),
        ),
    ]
