# Generated by Django 5.0.9 on 2024-09-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.TextField(blank=True, max_length=50, null=True)),
                ('ean', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('achat_brut', models.FloatField(blank=True, null=True)),
                ('achat_net', models.FloatField(blank=True, null=True)),
                ('achat_tva', models.FloatField(blank=True, null=True)),
                ('coef_marge', models.FloatField(blank=True, null=True)),
                ('vente_net', models.FloatField(blank=True, null=True)),
                ('vente_tva', models.FloatField(blank=True, null=True)),
                ('incremental_option', models.CharField(choices=[('quantity', 'Quantity'), ('weight', 'Weight')], default='weight', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=3)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Inventory', max_length=100)),
                ('last_response', models.TextField(default='Comment puis-je vous aider ?')),
                ('products', models.ManyToManyField(to='inventory.product')),
                ('transaction_list', models.ManyToManyField(to='inventory.stocktransaction')),
            ],
        ),
    ]
