# Generated by Django 5.0.9 on 2024-11-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('achat_brut', models.FloatField(default=0.0)),
                ('achat_net', models.FloatField(blank=True, null=True)),
                ('achat_tva', models.FloatField(blank=True, null=True)),
                ('coef_marge', models.FloatField(blank=True, null=True)),
                ('vente_net', models.FloatField(blank=True, null=True)),
                ('vente_tva', models.FloatField(blank=True, null=True)),
                ('code_art', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('has_changed', models.BooleanField(default=False)),
                ('incremental_option', models.CharField(choices=[('quantity', 'Quantity'), ('weight', 'Weight')], default='weight', max_length=20)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=3)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Inventory', max_length=50, unique=True)),
                ('last_response', models.TextField(default='Comment puis-je vous aider ?')),
                ('code_nomenclature', models.CharField(default='DFT', max_length=3, unique=True)),
                ('products', models.ManyToManyField(to='inventory.product')),
                ('transaction_list', models.ManyToManyField(to='inventory.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
