# Generated by Django 5.0.9 on 2024-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_response',
            field=models.TextField(default='Comment puis-je vous aider ?'),
        ),
    ]
