# Generated by Django 5.0.9 on 2024-09-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
