# Generated by Django 5.0.8 on 2024-09-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='My Inventory', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
