# Generated by Django 5.0.9 on 2024-11-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='code_nomenclature',
        ),
    ]
