# Generated by Django 5.0.9 on 2024-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='My Inventory', max_length=50, unique=True),
        ),
    ]
