# Generated by Django 5.0.9 on 2024-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_name_alter_inventory_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='attributes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.CharField(blank=True, null=True),
        ),
    ]
