# Generated by Django 5.0.9 on 2024-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_name_inventory_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='My Inventory', max_length=100),
        ),
    ]
