# Generated by Django 5.0.9 on 2024-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='attributes',
        ),
        migrations.AddField(
            model_name='inventory',
            name='dtypes',
            field=models.TextField(blank=True, help_text='data types, seperated by new line', null=True),
        ),
    ]
