# Generated by Django 5.0.9 on 2024-10-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('n_tva', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('tva', models.FloatField(blank=True, default=20.0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.provider'),
        ),
    ]
