# Generated by Django 5.0.9 on 2024-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventory_attributes_inventory_dtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('quantity', 'Quantity'), ('name', 'Name'), ('weight', 'Weight'), ('price', 'Price')])),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='inventory',
            name='dtypes_array',
            field=models.TextField(blank=True, help_text='data types, seperated by new line', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_field_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='incremental_option',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('weight', 'Weight')], default='weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='dtypes',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('COLIS', 'Colis'), ('KG', 'Kg'), ('G', 'Grammes')], default='KG'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='dtypes',
            field=models.ManyToManyField(to='inventory.inventorydatatype'),
        ),
    ]
