# Generated by Django 5.0.9 on 2024-10-08 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_provider_alter_product_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.provider'),
        ),
    ]
