# Generated by Django 5.0.9 on 2024-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorydatatype_remove_product_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='entry_list',
            field=models.ManyToManyField(to='inventory.stockentry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
