# Generated by Django 5.0.9 on 2024-10-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_fournisseur'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provider.provider'),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
