# Generated by Django 5.0.9 on 2024-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_fournisseur_delete_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_changed',
            field=models.BooleanField(default=False),
        ),
    ]
