# Generated by Django 5.0.9 on 2024-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lot_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
