# Generated by Django 5.0.9 on 2024-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='inventory_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
