# Generated by Django 5.0.9 on 2024-10-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_delivery_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='code_nomenclature',
            field=models.CharField(default='DFT', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
