# Generated by Django 5.0.9 on 2024-09-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_lot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydatatype',
            name='data_type',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('name', 'Name'), ('weight', 'Weight'), ('price', 'Price')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='incremental_option',
            field=models.CharField(choices=[('quantity', 'Quantity'), ('weight', 'Weight')], default='weight', max_length=20),
        ),
    ]
