# Generated by Django 5.0.9 on 2024-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventory_code_nomenclature_product_internal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='achat_brut',
            field=models.FloatField(default=0.0),
        ),
    ]
