# Generated by Django 5.0.9 on 2024-09-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorydatatype_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='dtypes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_field_2',
        ),
        migrations.AddField(
            model_name='product',
            name='achat_net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='achat_tva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coef_marge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vente_net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vente_tva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InventoryDataType',
        ),
    ]
