# Generated by Django 5.0.9 on 2024-10-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_alter_backup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='name',
        ),
    ]
