# Generated by Django 5.0.9 on 2024-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('n_tva', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('tva', models.FloatField(blank=True, default=20.0, null=True)),
            ],
        ),
    ]
