# Generated by Django 5.0.9 on 2024-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='n_tva',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='tva',
        ),
        migrations.AddField(
            model_name='provider',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
