name: 2 - Delete Media File Worker

on:
  workflow_dispatch:
  schedule:
   - cron: '0 1 * * *'
  # - cron: '0 4 1 * *'

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 0
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
      NEON_PROD_BRANCH: "main"
    steps:
      - name: Delete Media File
        working-directory: ./media
        run: |
          rm ./*